AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/20200923234059_devise_token_auth_create_users.rb'
    - 'bin/*'
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Layout/LineLength:
  Exclude:
    - 'app/views/api/v1/**/*.json.jbuilder'
    - 'app/views/api/v1/**/**/*.json.jbuilder'
Style/Documentation:
  Enabled: false

