AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'config/initializers/pagy.rb'
    - 'config/environments/*'
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Metrics/MethodLength:
  Exclude:
    - 'app/models/feed.rb'
Layout/LineLength:
  Exclude:
    - 'app/views/api/v1/**/*.json.jbuilder'
    - 'app/views/api/v1/**/**/*.json.jbuilder'
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"
Metrics/ClassLength:
  Exclude:
    - 'app/models/event.rb'
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - app/models/question/multi_select.rb
    - app/models/question/multiple_choice.rb
    - app/models/question/numeric.rb
    - app/models/question/text.rb
    - app/models/question/range.rb



