AllCops:
  Exclude:
    - 'db/*'
    - 'bin/*'
    - 'config/initializers/pagy.rb'
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Style/Documentation:
  Enabled: false
